# Generated by Django 4.1.5 on 2023-02-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=models.EmailField(max_length=254, unique=True, verbose_name='Почта'), max_length=200, null=True),
        ),
    ]
