# Generated by Django 4.1.5 on 2023-01-21 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailingSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True)),
                ('period', models.CharField(blank=True, choices=[('один раз в день', 'один раз в день'), ('один раз в неделю', 'один раз в неделю'), ('один раз в месяц', 'один раз в месяц')], default='UTC', max_length=250, null=True)),
                ('sending_status', models.CharField(choices=[('sent', 'Sent'), ('not sent', 'Not sent'), ('created', 'created')], default='created', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MessageForSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(blank=True, max_length=250, null=True)),
                ('preview', models.CharField(blank=True, max_length=200, null=True)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.mailingsetup')),
            ],
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.CharField(max_length=150)),
                ('server_response', models.CharField(blank=True, max_length=250, null=True)),
                ('id_message_for_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.messageforsend')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.mailingsetup')),
            ],
        ),
    ]
