# Generated by Django 4.1.5 on 2023-01-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageforsend',
            name='last_time_sending',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
