# Generated by Django 4.1.5 on 2023-02-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageforsend',
            options={'permissions': [('set_status', 'Изменить статус')], 'verbose_name': 'Сообщение для рассылки', 'verbose_name_plural': 'Сообщения для рассылки'},
        ),
    ]
